import type { Scene } from "@demo/runtime";

export const TOTAL_STEPS = 8;

export const scenes: Scene[] = [
  {
    id: "s1-fleet",
    step: 1,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "Booth fleet",
    hint: "Six in-process emulators. Tap Lobby Cam, or Continue.",
    choices: [{ id: "next", label: "Open Lobby Cam", next: "s2-lossy", variant: "primary" }],
    payload: { view: "fleet", reset: true },
  },
  {
    id: "s2-lossy",
    step: 2,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "40% loss",
    hint: "Retries + backoff. Tile stays green — no false alarm.",
    choices: [{ id: "next", label: "Watch the fleet", next: "s3-still-up", variant: "primary" }],
    payload: {
      view: "detail",
      focusId: "lobby-cam",
      inject: { id: "lobby-cam", fault: "lossy" },
    },
  },
  {
    id: "s3-still-up",
    step: 3,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "Still up",
    hint: "Down needs 4 consecutive misses. Lossy path stays honest.",
    choices: [{ id: "next", label: "Hard-kill the cam", next: "s4-kill", variant: "primary" }],
    payload: { view: "fleet" },
  },
  {
    id: "s4-kill",
    step: 4,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "Hard kill",
    hint: "Circuit opens after 4 misses. Watch it go red.",
    choices: [{ id: "next", label: "See it down", next: "s5-down", variant: "primary" }],
    payload: {
      view: "detail",
      focusId: "lobby-cam",
      inject: { id: "lobby-cam", fault: "dead" },
    },
  },
  {
    id: "s5-down",
    step: 5,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "Honest down",
    hint: "Now add another emulator — no restart.",
    choices: [{ id: "next", label: "Add emulator", next: "s6-add", variant: "primary" }],
    payload: { view: "fleet" },
  },
  {
    id: "s6-add",
    step: 6,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "Spin up",
    hint: "Change the form or use the default Patio Cam.",
    choices: [{ id: "next", label: "Back to fleet", next: "s7-spawned", variant: "primary" }],
    payload: { view: "add" },
  },
  {
    id: "s7-spawned",
    step: 7,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "Live add",
    hint: "New device is already being polled. Recover the camera.",
    choices: [{ id: "next", label: "Recover Lobby Cam", next: "s8-recover", variant: "primary" }],
    payload: {
      view: "fleet",
      spawn: { name: "Patio Cam", kind: "camera", protocol: "grpc" },
    },
  },
  {
    id: "s8-recover",
    step: 8,
    totalSteps: TOTAL_STEPS,
    device: "ops",
    app: "devices",
    title: "Recover",
    hint: "DEGRADED then UP. Tap around — this dashboard is live.",
    next: "s1-fleet",
    choices: [{ id: "replay", label: "Replay tour", next: "s1-fleet", variant: "primary" }],
    payload: {
      view: "detail",
      focusId: "lobby-cam",
      inject: { id: "lobby-cam", fault: "none" },
    },
  },
];
