import type { PersonId } from "./model";

const CS: Record<string, string> = {
  en: "angličtina",
  cs: "čeština",
  Untitled: "Bez názvu",
  Create: "Vytvořit",
  Cancel: "Zrušit",
  Summary: "Shrnutí",
  Room: "Místnost",
  Playbook: "Postup",
  Todos: "Úkoly",
  Description: "Popis",
  "Create mission": "Nová mise",
  Stakeholder: "Účast",
  Accept: "Přijmout",
  Garbage: "Zahodit",
  Back: "Zpět",
  "Add checkpoint": "Přidat krok",
  done: "hotovo",
  garbage: "koš",
  "Product owner": "Product owner",
  "UX designer": "UX designér",
  Product: "Produkt",
  Activation: "Aktivace",
  "Pricing and checkout": "Ceny a pokladna",
  "First session": "První spuštění",
  Ship: "Dodat",
  Decide: "Rozhodnutí",
  Build: "Postavit",
  Frame: "Rámec",
  Spec: "Specifikace",
  Design: "Návrh",
  Implement: "Implementace",
  Verify: "Ověření",
  Options: "Možnosti",
  Record: "Záznam",
  Research: "Průzkum",
  Review: "Revize",
  Handoff: "Předání",
  Draft: "Koncept",
  "Legal copy": "Právní text",
  Decision: "Rozhodnutí",
  Diff: "Diff",
  Check: "Kontrola",
  Copy: "Text",
  "Pricing page hierarchy": "Hierarchie ceníku",
  "Prorate plan changes": "Poměrná změna plánu",
  "Free tier limits": "Limity free tarifu",
  "Pricing empty state": "Prázdný stav ceníku",
  "Onboarding checklist": "Checklist nástupu",
  "Annual as default": "Roční cena jako výchozí",
  "Year price leads.": "Roční cena je první.",
  "Annual card leads": "Roční karta vede",
  "Month as a quiet second line": "Měsíc jako tichý druhý řádek",
  "Upgrade mid-cycle": "Upgrade uprostřed cyklu",
  "Credit unused days": "Vrátit nevyužité dny",
  "Pick the event cap": "Zvolit limit událostí",
  "First-run steps": "Kroky prvního spuštění",
  "Write the decision": "Napsat rozhodnutí",
  "Hierarchy spec": "Specifikace hierarchie",
  "Annual card first": "Roční karta první",
  "Proration note": "Poznámka k poměrné částce",
  "Per day, not per cent": "Po dnech, ne po centech",
  "Limit options": "Varianty limitu",
  "100 or 1,000 events": "100 nebo 1 000 událostí",
  "Annual default": "Roční výchozí",
  "Year price first": "Nejdřív roční cena",
  "Pricing spec": "Specifikace ceny",
  "Annual card, month as a second line": "Roční karta, měsíc jako druhý řádek",
  "Pricing layout": "Rozvržení ceny",
  "Annual card on top": "Roční karta nahoře",
  "Pricing diff": "Diff ceny",
  "Hero price block": "Blok hlavní ceny",
  Verification: "Ověření",
  "Checks green": "Kontroly jsou zelené",
  "Annual price, tax note": "Roční cena, poznámka k dani",
};

export function tr(person: PersonId, text: string): string {
  if (person !== "lea" || !text) return text;
  return CS[text] ?? text;
}
